### PR TITLE
Add no rp speak in the pr guidlines

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
We (try) to enforce it. May as well make sure its in here to be enforced.

### CODE REVIEW

**Comment by Errant-4** [comment]
I uh, I must point out that you did not end either of the "Good" examples with a . and thus fail our CL guidelines

**Comment by VasilisThePikachu** [comment]
> I uh, I must point out that you did not end either of the "Good" examples with a . and thus fail our CL guidelines
> 
> Funny changelogs will always live on in my heart but you do have a point, this is the way forward now

bruh

**Comment by BasedUser** [comment]
good this makes sense

**Review by Partmedia — APPROVED** [review]
I see this as part of "be concise", because RP-speak obfuscates what actually changed. But I'm happy with this change as well. Leaving open in case you want to copy edit a bit. It would be good to explain why you shouldn't use "RP speak", and the reason is it conflicts with "be concise" and to the point.

**Comment by VasilisThePikachu** [comment]
> I see this as part of "be concise", because RP-speak obfuscates what actually changed. But I'm happy with this change as well. Leaving open in case you want to copy edit a bit. It would be good to explain why you shouldn't use "RP speak", and the reason is it conflicts with "be concise" and to the point.

"be concise" is a pretty weird wording to use for it. I will just play it safe and keep it separate unless someone who knows english can word it better

**Comment by Partmedia** [comment]
I've made some edits and merged. Thanks.

**Pull request merged**
