### PR TITLE
Courier Job

### PR DESCRIPTION
**Pull request by Hanzdegloker**
I've done this as an unofficial job being a Cargo tech, I've had Cargotechs do multiple deliveries for me as QM. Not to mention I vaguely remember it being a job on some ss13 servers. Eitherway I'd like for it to be a formal job that encourages learning maps, talking to people, and ensuring the mail is always delivered on time no matter what!

### CODE REVIEW

**Comment by Aisu9** [comment]
aren't cargo techy supposed to deal with big request and deliver them to people? the courier should be busy 24/7 delivering and running after people for their mail

**Comment by K-Dynamic** [comment]
Cargo techs and couriers by extension don't like to deliver stuff because it's so slow and needs multiple trips for multiple crates

Better idea would be to give cargo a forklit or roundstart ripley on more maps

**Comment by Aisu9** [comment]
other than that they can always wait for the lazy crew to grab their delivery waiting in cargo, gotta force them to talk a little bit and come out of their departement

**Comment by Hanzdegloker** [comment]
While the job would help cargo, I imagine more scenarios like delivering food to the warden who is tied up at sec, bringing medicinal plants from botany to chemistry, or perhaps even just delivering a gift from one person to another. Hell, delivering letters.

**Comment by EmoGarbage404** [comment]
i really don't see how this job is distinct enough from cargo technicians. As it stands, cargo techs are already in a bad place content-wise. I don't think that splitting off more of their tasks into a new job would really be beneficial.

**Comment by lzk228** [comment]
cargo thechnician 2.0

**Comment by Hanzdegloker** [comment]
> i really don't see how this job is distinct enough from cargo technicians. As it stands, cargo techs are already in a bad place content-wise. I don't think that splitting off more of their tasks into a new job would really be beneficial.

Should I rather take the ideas behind the courier and just implement it for the cargo tech? I do just love the idea of packages and letters as well as delivering goods. I can rework it to act as an additional part of cargo tech duties. Go to cargo and request they send a package or letter to someone. Requesting a cargo tech help transport goods between say sci and sec.

**Comment by LordEclipse** [comment]
> > i really don't see how this job is distinct enough from cargo technicians. As it stands, cargo techs are already in a bad place content-wise. I don't think that splitting off more of their tasks into a new job would really be beneficial.
> 
> Should I rather take the ideas behind the courier and just implement it for the cargo tech? I do just love the idea of packages and letters as well as delivering goods. I can rework it to act as an additional part of cargo tech duties. Go to cargo and request they send a package or letter to someone. Requesting a cargo tech help transport goods between say sci and sec.

IMO yes, it gives cargo techs more to do

**Comment by Hanzdegloker** [comment]
Ideas from this document will be reworked and given to cargo techs to attempt to add more things for cargo tech to do

**Pull request closed without merging**
