### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by Fromoriss**
Yeah, in future it will be Ukrainian translation for docs.

### CODE REVIEW

**Comment by lzk228** [comment]
ahh i was thinking about it first :trollface:

**Review by lzk228 — CHANGES_REQUESTED** [review]
you need to create new directory, `src/ua/...`, like in #62

**Comment by Fromoriss** [comment]
Our community will be make it, I was committed to it only for PR creation.

**Comment by lzk228** [comment]
guys, even if you arent working on it, it would be REALLY better to make a lot small prs instead of one huge with all translation

**Comment by Jezithyr** [comment]
Closed as part of the docs repo cleanup. If you are still actively working on this PR feel free to reopen it.

**Pull request closed without merging**
