### PR TITLE
Cleanup crew gamemode

### PR DESCRIPTION
**Pull request by mirrorcult**
another idea i've had forever that im just rewriting for the docs site

### CODE REVIEW

**Comment by mirrorcult** [comment]
i honestly feel so strongly that this will be a cool concept that i want to make it somehow work for higher pop (like up to ~50 players maybe?) but im not sure how i could accomplish that, i think it gets too chaotic at that point

**Comment by mirrorcult** [comment]
you -could- turn it into a competitive-cooperative gamemode by just spawning 2 stations on different maps and spawning half of the players on one of them and half of them on the other :trollface:

**Comment by deltanedas** [comment]
also depending on how things are weighted, you could force save a map by setting every air alarm to siphon before round end, then all your toilets will live on

**Comment by mirrorcult** [comment]
wait, that actually kind of goes hard

**Comment by mirrorcult** [comment]
my idea not the toilets

**Comment by deltanedas** [comment]
:trollface:

**Comment by deltanedas** [comment]
i think the competitive idea would be better for 50+ players, with 20p splitting them like that would be too detrimental imo as it would take too long to do anything

**Comment by mirrorcult** [comment]
yeah im talking about for multiples of 20p

**Comment by Emisse** [comment]
ideagirl write skibidi toiler doc

**Comment by mirrorcult** [comment]
Nuts -> My Mouth

**Comment by chromiumboy** [comment]
Ooo, for the high pop version, spawn half the players on a normal low pop station, the other half on the derelict who are there to repair it. When time runs out, the crew on the first station get transfered over to the repaired derelict via where the round continues

**Comment by deltanedas** [comment]
and they dont know the gamemode so when they think round is about to end they get sent to brazil :trollface:

**Comment by chromiumboy** [comment]
> and they dont know the gamemode so when they think round is about to end they get sent to brazil :trollface:

Worse, Barratry v2.0 :trollface:

**Comment by mirrorcult** [comment]
you can read it and decide for yourself if you think it would be viscera cleanup detail the game mode

**Comment by mirrorcult** [comment]
the selfmerger

**Comment by Rainbeon** [comment]
very good

**Pull request merged**
