### PR TITLE
Departmental Economy

### PR DESCRIPTION
**Pull request by mirrorcult**
mirconomy

couple ideas ive had for years + some new concepts i developed recently that i think solve a couple huge design issues / give us some breathing room with them + introduce a ton of new gameplay

### CODE REVIEW

**Comment by K-Dynamic** [comment]
If NT starts paying out to the station, you could feasibly pay workers too, add payments to vendors and watch the mayhem when the spesos crash event is added :trollface: 

For the MULE or dollies to deliver bulk items, that can be implemented immediately if mappers add a roundstart Ripley w/ 4-storage hamtr clamp to cargo (10-storage ripley clamp too powerful for roundstart) or a single gravity gun for cargo

Out of scope but I'd love to also see antag objectives based on money (payday the heist :trollface: ) and space IRS that gets pissed if the station makes too much money and evades taxes

**Comment by Nimfar11** [comment]
Will the money come from how bad things are at the station or conversely, how good things are? Because it can happen that the engineers are extremely sloppy and the medics are not so diligent in treating so that there is more destruction, more wounded and dead, which will bring more money. The better the station is, despite negative events, the more money should come in. This way the departments will do their jobs more responsibly.

**Comment by themias** [comment]
I really like this idea. NanoTrasen is supposed to be a dystopian MegaCorp, so making money more of a focus (without going full economy) is a good change.

The current experience or ordering from Cargo always seems like begging (if there's even anyone at the counter), so being able to directly make purchases with money your department earned will be nice.

I'd imagine the Lobbing Bundle is going to be much more popular. "Hey CE, I hear you're strapped for cash. I'll give you 30k for your boots, what do you say?" I'm always a fan of antags having more creative and non-violent ways of achieving their objectives.

**Comment by Hanzdegloker** [comment]
I always thought it was odd we are on a super corp station and all employees for this greedy corp. And all vending machines are free, food and drinks are free. Cargo does handouts. I feel like the tiny charges to your account when using a vending machine didn't mean much in whether or not you could afford to eat, vending machines snacks are cheap enough. But it seals the atmosphere and setting of the game!

Also players online ordering stuff with money and Cargo becomes Amazon???

**Comment by PJB3005** [comment]
Lockboxes being truly indestructible sounds icky because it generally is in SS13. I assume there reason is because "sec sells high-value shit -> cargo steals it instead". Maybe make the lockboxes have an alarm if opened by brute force and it'd notify sec?

**Comment by deltanedas** [comment]
i hate the idea of a department not doing their job = they get paid more

what it will mean is shitters will make bats and spears roundstart, start shocking doors, cut wires to outside engi and kill anyone that breaks in. they have financial incentive for this extreme selfantagging which is bad

**Comment by mirrorcult** [comment]
> Lockboxes being truly indestructible sounds icky because it generally is in SS13. 

i agree and im not attached to it being indestructible, i just want some way to heavily disincentivize cargo breaking into them instead of selling them--an alarm would also be neat

> I feel like the tiny charges to your account when using a vending machine didn't mean much in whether or not you could afford to eat, vending machines snacks are cheap enough. But it seals the atmosphere and setting of the game!

i dont plan to add this in any capacity, its not part of the doc

> they have financial incentive for this extreme selfantagging which is bad
> 

i dont disagree that it could turn out problematic but financial incentive which they will then use to purchase what exactly? the main thing departments are going to want are things to do their job in the first place. theres zero logical reason to break a bunch of shit so you can get money to buy supplies to fix the shit you just broke

**Comment by deltanedas** [comment]
presumably engi will then use all their blood money to buy 800 gorillas, then declare war on cargo to take it all back to engi safely

**Comment by mirrorcult** [comment]
do you legitimately believe this is a likely outcome

**Comment by UbaserB** [comment]
What if you spend department funds and then cargo ends up using the crate thinking they purchased it instead of XX department? Also, science is surprisingly low at 15% when they need a lot of resources.

**Comment by deltanedas** [comment]
yes

also a potential alternative to lockboxes is having each department able to sell things, but they get a cheque from centcom that says how much money cargo and whatever department that sold it gets

so sec sells their armoury and gets a fat check with 12k for sec 4k to cargo then they hand it to cargo to properly sell / cash in and then both balances are updated

**Comment by UbaserB** [comment]
nevermind i read the comments and lockboxes are a thing. Anyway, the science point is still valid

**Comment by mirrorcult** [comment]
i think a solution is probably to be more granular with which metrics actually have which effect. i.e. having hostile mobs / anomalies / other sources of danger is rewarded but having people dead/power out is penalized, so its more about having as much danger as possible while still surviving

**Comment by mirrorcult** [comment]
> also a potential alternative to lockboxes is having each department able to sell things, but they get a cheque from centcom that says how much money cargo and whatever department that sold it gets
> 

the reason i didnt do something like this is because 'having each department able to sell things' how and where?

**Comment by mirrorcult** [comment]
> What if you spend department funds and then cargo ends up using the crate thinking they purchased it instead of XX department? Also, science is surprisingly low at 15% when they need a lot of resources.

if cargo steals the stuff other departments bought (which should also be access locked generally) then thats pretty firmly an issue that should get handled in character

sci is at 15% because theyre expected to make back some profit from selling stuff. might increase regardless

**Comment by deltanedas** [comment]
a single sale console and palette in each department, then require palettes be linked with multitool instead of selling the entire grid's palettes in 1 click

**Comment by mirrorcult** [comment]
so cargo shuttle/trade station becomes irrelevant?

**Comment by deltanedas** [comment]
but instead of making money it makes a cheque

**Comment by mirrorcult** [comment]
that potentially works but i think people will be confused why it doesnt just give them money instead of giving them a thing that gives them money when sold

**Comment by deltanedas** [comment]
it also gives money to cargo instead of just them, if it just gave them a 100% share cheque then yes it would be sus

**Comment by mirrorcult** [comment]
i think theres probably a better way to go about it than that, i dont like selling for depts having basically zero friction

**Comment by K-Dynamic** [comment]
> a single sale console and palette in each department, then require palettes be linked with multitool instead of selling the entire grid's palettes in 1 click

Order console in each dept or public area good, sales console bad (imagine a shitter selling off important equipment or contraband/evidence being sold off

**Comment by PolterTzi** [comment]
I know my opinion isn't exactly valued highly here, but I'm somewhat concerned this kind of economy could potentially be detrimental to cooperation between departments by adding incentives to be more selfish and demand money for services that would normally be rendered as a matter of course, potentially introducing friction to virtually any cross-department interaction, adding a negotiation and transfer step to previously simple requests. I hope that's not gonna become an issue, but I wanted to note the concern.
I also feel giving all departments the option to sell stuff for their own budget (even if they need cargo's help) _might_ potentially end up with the gameplay of the department getting recentered on production of sellable commodities over their main job.

**Comment by mirrorcult** [comment]
> I know my opinion isn't exactly valued highly here

any opinion is valued here as long as its argued in good faith, these are public for a reason!

> but I'm somewhat concerned this kind of economy could potentially be detrimental to cooperation between departments by adding incentives to be more selfish and demand money for services that would normally be rendered as a matter of course

its a valid concern--i dont anticipate it being so ingrained that depts will feel the need to haggle in every possible situation. people will probably overplay it when its initially added just to have fun with it but i don't think people will want to introduce extra friction except for situations where they can benefit a lot or where they can find some fun roleplay scenario along with it. with the reduced friction that comes with more dept agency i think the potential increased friction of dept cooperation will be a lot more manageable (and actually more fun to manage)

> _might_ potentially end up with the gameplay of the department getting recentered on production of sellable commodities over their main job.

this is mostly why i want some friction for departmental selling (i.e. no sale pallets in depts). ideally some players in depts like sci/botany want to make some extra cash selling stuff but that should be primarily relegated to cargo trying to make money. if people are too profit driven in depts where doing that isnt interesting (like med or engi mamostly i would expect depts to use it as a bargaining chip in situationybe) we can think about disincentivizing it more, but we'd have to see

**Comment by metalgearsloth** [comment]
- Like the idea of decentralising cargo ordering
- Not sure how to feel about dynamic passive income

On the gameplay side there's probably a technical name for this but this is somewhat similar to how people handle DND resurrections:
Option A you use party funds to revive people so there's no direct incentive to being selfish.
Option B you use personal funds and as a result people are much more inclined to be selfish / steal funds.

I imagine an implementation would require admin consultation first given stealing other departments stuff for your own would probably be considered self-antagging and they would be rewarded for it.

**Comment by IProduceWidgets** [comment]
I think the managing of department income should be a captain thing since it's likely going to mostly be head interaction and that doesn't make the most sense for hop.

I am weary about the income sources. Using it as a mercy mechanic causes odd incentives.

**Comment by deltanedas** [comment]
were so back

**Comment by Djungelskog2** [comment]
a few questions about lockboxes
What do you mean lockboxes to sell things? are they infinite? where do you get them from? what stuff (of monetary value) do you expect to put in there?

**Comment by EthanQix** [comment]
This is so much more interesting design than just a "personal" economy where everyone needs to carry spesos to eat at the cafeteria.

**Comment by mirrorcult** [comment]
for context some other thoughts from me & flare discussing it a little further https://discord.com/channels/310555209753690112/770682801607278632/1289872208591847454

negative incentive stuff is going away probably if i implement this
need to think on how lockboxes will work a little more probably, its weird to get the design right

**Comment by DoguhanOzgurAkca** [comment]
Huh, first comment here.  Anyways
I was discussing ideas with some chemists the other day and we had the idea about chemist having more things to do, especially silly things, but there were some problems with it of course, such as how they need to be limited and all
Medical department funds might be able to fix that issue if the chemist first needs to make money to buy things that allow the silliness. I think it can be added to like every department, some kind of a way to make a little bit of money on the side for the things they are going to order. I understand adding some kind of a money making thing to every department might be hard but a lot of the departments don't really need a way to make money on the account that they don't need anything from cargo, not now at least. 
Plus, I would just love to see chemists turn i don't know, copper into gold or something like that. Just a silly idea heh.

I think it might help with the lockboxes a bit as well? In the round-start, you just have a half-full departmental box with things that the department produce to make money that can be used continuously.
One last idea is that if we have a console that can take the money from other departments and all, we can have pirate raids whose plan is to just get all of that money.  Some sort of alternative to nukies, but perhaps instead of being round start, its mid-round like an event if there are a lot of dead players?
I wrote too long... anyways, I love the system. I hope it gets implemented.

**Pull request merged**
