### PR TITLE
Automated Evac & Crew Transfers [Moony]

### PR DESCRIPTION
**Pull request by TemporalOroboros**
Unapproved so keep as a PR for now.

Requires #35

### CODE REVIEW

**Comment by LankLTE** [comment]
@moonheart08 Do you wish to have this reviewed still?

**Comment by moonheart08** [comment]
I will not be available to actually steward it. I can implement it, but I don't desire to interact with the community at this time.

**Comment by moonheart08** [comment]
Additionally, this is a hackmd port. When this was originally written the evac shuttle was not fully implemented and the idea of autopilot (full vessel movement) was still around.

**Comment by LankLTE** [comment]
> I will not be available to actually steward it. 

That's fine. We can still discuss it and put a result here, if you'd like, obviously keeping in mind how sort of outdated it is now.

**Comment by PJB3005** [comment]
We've decided to close this proposal after review in the last maintainer meeting. Here are the notes: https://docs.spacestation14.com/en/maintainer-meetings/maintainer-meeting-2024-03-23.html#design-docs

**Pull request closed without merging**
