### PR TITLE
The Controller Brain

### PR DESCRIPTION
**Pull request by Veritius**
A fleshy mid-round conversion antag.

**It's already inside your head.**

### CODE REVIEW

**Comment by Veritius** [comment]
todo: make this not a blob knockoff

**Comment by Ilya246** [comment]
meat blob is real
could be nice if this was blob but more focused on converting the station and not colonising it

**Comment by Ilya246** [comment]
definitely needs more stuff to do, my suggestions listed here
- invisible tendrils it can spread across the station at the cost of points, grants vision (might actually have a way of being spotted, thermal googles then since nobody just randomly uses those?), *may be built under doors*
- expensive invisibility it can buy for itself (it's stealthbox invisibility where it's actually visible if you look hard enough), would require it to be spotted by tracing it through tendrils
- ability to relocate itself to anywhere on its tendrils, at a cost
- other types of thralls, perhaps a tank (high health + regen) type and a slasher (high speed and high DPS) type
- other buildings it can build on tendrils
- building: transportation canal, allows thralls to teleport to any other canal

**Comment by Jezithyr** [comment]
Closed as part of the docs repo cleanup. If you are still actively working on this PR feel free to reopen it.

**Pull request closed without merging**
