### PR TITLE
Revolution Gamemode Rework

### PR DESCRIPTION
**Pull request by SpeltIncorrectyl**
Another proposal for reworking the revolution gamemode.

### CODE REVIEW

**Comment by Aisu9** [comment]
please anything that doesn't turn Rev into a fucking team deathmatch

**Comment by SpeltIncorrectyl** [comment]
> please anything that doesn't turn Rev into a fucking team deathmatch

Revs was always a deathmatch. It's two teams trying to kill each other.

**Comment by SpeltIncorrectyl** [comment]
Sec gets meds so they can revive and convert revs they kill defending a telecrate.

**Comment by Aisu9** [comment]
it's command/sec again revs. not command/security again rev again civilians. there was MANY complain about revs being murderbones not giving a shit about civilians just spraying them full of lead, even if they were no threat to the revolution.
if you can make suggest an un-removable implant that make headrevs and revs taking genetics damage if they **hurt** an unarmed civilians that would be perfect.
The gamomodewas removed because of the murderbone tendency the community have. THIS is why need to be fixed

**Comment by Hmeister-real** [comment]
> it's command/sec again revs. not command/security again rev again civilians. there was MANY complain about revs being murderbones not giving a shit about civilians just spraying them full of lead, even if they were no threat to the revolution. if you can suggest an un-removable implant that make headrevs and revs taking genetics damage if they **hurt** an unarmed civilians that would be perfect. The game mode was removed because of the murderbone tendency the community have. THIS is what need to be fixed

Maybe rather than direct damage, if you hurt someone who doesn't have a mindshield you begin to take direct hunger damage, and start vomiting? I don't like the idea of a clown blocking my automatic rifle fire from outside of my vision radius and then me taking more than half my health of gene damage of no fault of my own, and so just losing hunger prevents that a little and lets you know that you should stop.

**Comment by Hmeister-real** [comment]
> Maybe rather than direct damage, if you hurt someone who doesn't have a mindshield you begin to take direct hunger damage, and start vomiting? I don't like the idea of a clown blocking my automatic rifle fire from outside of my vision radius and then me taking more than half my health of gene damage of no fault of my own, and so just losing hunger prevents that a little and lets you know that you should stop.

Also also, gives you a reason to keep certain roles like chefs and service assistants alive without needing to add a direct consequence since you cant feed a revolution on vending machine crap, especially when paychecks and vending machine prices are added

**Comment by Aisu9** [comment]
> > Maybe rather than direct damage, if you hurt someone who doesn't have a mindshield you begin to take direct hunger damage, and start vomiting? I don't like the idea of a clown blocking my automatic rifle fire from outside of my vision radius and then me taking more than half my health of gene damage of no fault of my own, and so just losing hunger prevents that a little and lets you know that you should stop.
> 
> Also also, gives you a reason to keep certain roles like chefs and service assistants alive without needing to add a direct consequence since you cant feed a revolution on vending machine crap, especially when paychecks and vending machine prices are added

personal economy is vetoed out... and emergency pizza crate cost nothing

**Pull request closed without merging**
