### PR TITLE
Thief design doc

### PR DESCRIPTION
**Pull request by TheShuEd**
I'm adding the design document of the new antagonist for discussion.
Open to criticism.

### CODE REVIEW

**Comment by mirrorcult** [comment]
add doc to index.md

**Comment by mirrorcult** [comment]
please include in summary.md & standardize in line with the [feature proposal reference](https://docs.spacestation14.com/en/proposals/proposal-template.html)

**Comment by UbaserB** [comment]
Shouldn't this be merged? Afterall, thief is in the game now.

**Comment by mirrorcult** [comment]
yes when its added to summary ill do it later if ed doesnt

**Review by LankLTE — APPROVED** [review]
There are apparently issues with the formatting, but I'm marking as approved as it's in the game.

**Pull request merged**
