### PR TITLE
Traitor variety

### PR DESCRIPTION
**Pull request by whateverusername0**
wololo
making this for [this](https://github.com/space-wizards/space-station-14/pull/28983)

### CODE REVIEW

**Comment by ElPidor** [comment]
DUDE YOU DONT KNOW ME I DONT KNOW YOU
BUT
YOU ARE THE BEST KEEP IT GOING!!!

**Comment by ElPidor** [comment]
so noone will review this doc? 😢

**Comment by whateverusername0** [comment]
after a lot of thinking i've decided to stop working on this
basically i stopped liking the idea of tator variety for no reason at all.
sorry wewalds 😔, you can use the branch of you wanna add it yourself i'm not completely deleting it

**Comment by TokenStyle** [comment]
I will takin'

**Pull request closed without merging**
