### PR TITLE
plant genetics design doc

### PR DESCRIPTION
**Pull request by deltanedas**
depends on botany ecs/rework design doc and could be reused with virology design doc

### CODE REVIEW

**Comment by Doru991** [comment]
I think this is kinda based, i've been thinking about having some kind of machine that you can use to edit plant genes like that and experiment each round to see what every DNA pair does, with the current plant genetics system it would be a bit painful to implement but if they had (for the most part) the gene system you proposed it'd feel pretty natural

**Comment by Ilya246** [comment]
i would suggest genes (both dangerous and good) that can only be enabled through gene editing, never randomly mutated

**Comment by deltanedas** [comment]
> genes (both dangerous and good) that can only be enabled through gene editing, never randomly mutated

yes i had the same little idea basically canary genes that kill the plant if modified, might be too annoying tho so idk

**Comment by Ilya246** [comment]
> yes i had the same little idea basically canary genes that kill the plant if modified, might be too annoying tho so idk

dangerous as in anywhere from killing the plant to poisoning anyone in the room

**Comment by deltanedas** [comment]
oh yeah i read in some commented out code that it used to be possible for plants to eat pests, and also eat people. would be cool to bring that back maybe

**Comment by drteaspoon420** [comment]
> i would suggest genes (both dangerous and good) that can only be enabled through gene editing, never randomly mutated as for costs, you could make a genome build up "genetic instability" as you edit it which makes further edits more expensive

I really dislike idea of arbitrary "genetic instability". There is such thing as damaged dna (missing instructions in dna, usually radiation knocking things out of place and causing tumors) but "genetic instability" is just nonsense.

I absolutely love the idea of having effectively 'binary' (quadnal? quadnary?) file of the seed and it's properties. I would also suggest moving from the 'viable' boolean system to 'sometimes the optimal growth conditions are just so out of reach that practically dies anyway.'
Currently optimal light, temperature, pressure etc. is in 'reasonable' limits, instead I would find it interesting if plants could go to 'unreasonable' spectrums in these things so that you might create a plant that survives in zero atmosphere or require close to zero kelvin enviorment with high pressure. Possibly make the mutagen style mutation into one that knocks these genomes one by one so increase in values can be in factors of 4 (0-3, per 'bit')

**Comment by deltanedas** [comment]
yeah perhaps instead of just "oops not allowed to grow" it suddenly wants to grow in a 40kK co2 atmosphere and refuses anything else, so if you were very very stubborn you *could* do it but realistically nobody would bother

**Comment by mirrorcult** [comment]
yes i like that better

**Comment by Ilya246** [comment]
> I really dislike idea of arbitrary "genetic instability". There is such thing as damaged dna (missing instructions in dna, usually radiation knocking things out of place and causing tumors) but "genetic instability" is just nonsense.

it's just for gene modification cost balance
if you don't like it, it would've been better if you at least suggested an alternative or how to rename it if you don't like the name specifically, since this is kind of needed so you can't just make everything into across-the-board superplants with no drawback

**Comment by drteaspoon420** [comment]
I am actually saying it's a non-issue. I am on the assumption that the dna file is fixed size. So you litterally can't have everything in same plant. Also with enough time and effort, why can't you achieve some sort of perfection or optimization?
I am sure the chemical/gas parts need to be completely reworked to exist in limited 'file size' so you litterally could not create a plant that does everything.
Example, lets make conjecture that there are only say 5 slots of DNA that goven what chemical a plant produces and I would assume it would have some sort of priority or weight based on the potency of the plant. Regardless of exact implementation details, as long as the 'file size' of plant dna is fixed it should be impossible to make 'super plant'.
Only way we could have superplants would be to implement atavism, and doubling the file size to count for suppressed genes.

**Comment by deltanedas** [comment]
> I am sure the chemical/gas parts need to be completely reworked to exist in limited 'file size' so you litterally could not create a plant that does everything.

anything using prototypes cant be in the genome, only bools and ints

so chemicals and gases cant be modified by gene editing at least not without some funny stuff

**Comment by drteaspoon420** [comment]
You can serialize that stuff into integers. Index of chemical, min, max, potency divisor.

**Comment by deltanedas** [comment]
reagent prototypes ids are strings and id really not index them by int
also being able to powergame bitflip into making romerol apples is no, since the ids numbers are probably predetermined

**Comment by drteaspoon420** [comment]
The system responsible for the handling of these dna changes and serialization can handle indexing the chems in random order. If player has to modify -> plant -> wait for growth to see results, likelyhood of player going through all of the +200 different chemicals that are in the game. Also the random index for chemical could be any between how ever many 'bytes' or genomes is assigned to the chemical index, leaving some completely blank, thus producing no chems at all.

**Comment by deltanedas** [comment]
also plant chemicals isnt just 1 id its a list of them along with quantities so that would have to be serialized too... not good

**Comment by drteaspoon420** [comment]
You could have limited 'slots'. While I admit that the plants with +20 chemicals are funny to make, most of them are just different alcoholic drinks or juiced plants.
Just add something like 5 to 10 'slots' to each plant. 4 genomes (8 bits, 1 byte) for id, 1 genomes for min, 1 for max, and 2 for potency divisor. That gives:
 - 256 chemical indexes (not sure how many chemicals we have but that should be nough, add 1 more gone if not. I am sure we are bellow 512)
 - 0-3 for min (+1, to keep it being zero)
 - 0-3 for max (maybe double it and add to min to keep reasonable, so 1-10)
 - 0-15 for potency divisor (add +1 and maybe multiply with 5 to to get range of 5-80)
 We could also skip the whole potency divisor because currently it is by default derived from max anyway. (100/max)
 In total 1 chemical serialization would be 6-8 Genomes (8 if you include potency divisor). so 5 would be 30-40 genomes and 10 would be 60-80.
 To be honest we could thin some fat from the system just by leaving in chemical index and max. If valid chemical index, have the minimum always be 1. Derive potency divisor always from the max instead of storing it in the seed.

**Comment by Doru991** [comment]
I honestly think we should just have a list of mutate-able reagents (since stuff like romerol/noct is obviously unbalanced and probably has no business being there and having a million cocktails that do the same things adds nothing to the experience) and just index based on that instead of every reagent ever

**Comment by drteaspoon420** [comment]
I agree partially. We should limit the chemical mutation by 'group' leaving out `Drinks`, possibly blacklist since there is more things we might want than not. I also think the fact that zombie infection comes from chemical like romerol is not desired in the long run but rather some seperate virus system. I am all for blacklisting romerol from the whole thing. Noct and other toxins are temporarry effects so I don't see point of blacklisting them as long as getting them through luck is once in a tens of games kind of thing.

**Comment by Doru991** [comment]
Yeah, I guess noct isn't that gamebreaking but romerol really has no place being there since it can potentially break a round and it's been previously stated that not even syndies should have access to it. As for blacklisting, I've generally seen whitelisting recommended as a better alternative since (in this case) some new reagents could be added in the future and slip through the blacklist leading to unintended access (like romerol currently is).

**Comment by deltanedas** [comment]
maybe have a whitelist of reagents that can be grown, then the genome can have up to 4 of them.
0 being nothing and anything else a 1-based index. only real issue with this is that reagents would have to be either written as ids in yaml which is godawful or have a separate reagent type for mapping it nicer

**Comment by drteaspoon420** [comment]
we can blacklist/whitelist based on group, since that is already part of the prototype for reagents. should reduce the work maintaining the system. And since we want every round to have different id for every chemical, just do it dynamically on system's initialize function.

**Comment by Partmedia** [comment]
I like the high level proposed mechanics. I encourage you to work on this piecemeal and PR as you go, e.g. by working out the changes to the data representation before you go ahead with everything as described.

**Comment by deltanedas** [comment]
yeah ill have to think about how to implement storing prototype ids generically so its not just limited to reagents

**Pull request merged**
