### PR TITLE
Rewrite/Edit General Development

### PR DESCRIPTION
**Pull request by Aeshus**
This is a large refactor of the `General Development` part of the wiki. Totally didn't start scope-creeping at the end!

Some changes were:
* Basically every page in General Development has been edited in some form.
  * I think Git for the SS14 Developer has the most significant editing.  
* There's a new `testing.md` page that's been requested for a while.
* Large refactor of the debugging page with pictures and more information.
* Edited the landing page and the indexing pages to be more clear and to describe the organizational structure of the docs.
* The order of stuff in the sidebar has been changed to "make more sense to me".
* Used admonitions significantly more, including collapsible ones! 
* Conventions now have a lot of direct examples from the current code-base to put it all in context.
* The index pages were moved into their respective directories with an index.md page.
* Moved all of the imgur photos to the repository.

There's still some todo's to finish (until this is ready to merge):
- Finish:
  - [x] the translation
  - [x] work-groups
  - [x] feature proposals
  - [x] and server hosting.
- [ ] Reread everything again to make sure grammar is all-good.
- [x] Create a custom admonition block so it stops spamming stdout(?).
* [ ] Bring back the `[friend()]` thing in conventions (or whatever it turned into)

### CODE REVIEW

**Comment by mirrorcult** [comment]
most zased pr 2024

**Comment by mirrorcult** [comment]
i would not touch the workgroups file in this PR, jez is doing her own things right now

**Comment by Aeshus** [comment]
> i would not touch the workgroups file in this PR, jez is doing her own things right now

Gotcha! While the changes were (hopefully) only syntactic, probably best to avoid any merge conflicts or interpretation changes.

I'll revert the file on this branch.

**Comment by Aeshus** [comment]
I haven't worked on this in a while and it's un-mergeable in its current state.

I'll divide up this PR at some point and try to merge in.

**Pull request closed without merging**
