### PR TITLE
Virology 2.0

### PR DESCRIPTION
**Pull request by drteaspoon420**
Draft of new virology proposal

### CODE REVIEW

**Comment by lzk228** [comment]
no way guys
virology just a week away

**Comment by drteaspoon420** [comment]
wait? is someone working on it?

**Comment by Jackal298** [comment]
> wait? is someone working on it?

As I understand it, this is a joke, it went from PR to surgery

**Comment by mirrorcult** [comment]
image

my opinions from discord

**Comment by mirrorcult** [comment]
please include in summary.md & standardize in line with the [feature proposal reference](https://docs.spacestation14.com/en/proposals/proposal-template.html)

**Comment by LankLTE** [comment]
Closing as no reply was given. Please request it be re-opened if you want it reviewed.

**Pull request closed without merging**
