### PR TITLE
Avali proposal

### PR DESCRIPTION
**Pull request by BackeTako**
New species Avali

Open to suggestions and willing to revise.

### CODE REVIEW

**Comment by Cadunkus** [comment]
Not okay with the fact that the only aliens ss13/14 players can come up with are "Earth human + Earth animal = have no connection to Earth".

While I don't mind lizardmen or moths (although their lore needs some work and they need actual alien names) because lizards and insectoids are sci-fi staples, other fiction like Halo, Star Wars, etc. tend to have more creative xeno races. Basically Avali oughta be more "alien species" and less "furry type".

**Comment by BackeTako** [comment]
> Not okay with the fact that the only aliens ss13/14 players can come up with are "Earth human + Earth animal = have no connection to Earth".

If you want diffrent types of species you can always write up another design document for it.
> While I don't mind lizardmen or moths (although their lore needs some work and they need actual alien names)

Just to be clear the lizardmen and moths dont have names and lore on purpose, and the maintainers have already shot down proposals for it since it limits the creativity and rp when you have predifined lore such as in [#29996](https://github.com/space-wizards/space-station-14/pull/29996).

**Comment by snebl** [comment]
I hope this gets approved. The last avali attempt was denied because its author was very stubborn about its balancing.

**Review by VasilisThePikachu — COMMENTED** [review]
i cant delete messages lmao ignore this

**Review by VasilisThePikachu — CHANGES_REQUESTED** [review]
Hello, fellow chicken nugget here.

This proposal is a better step than the previous ones. 

However, both lack to explain why this would be good to have in the game and only lay out features.

https://docs.spacestation14.com/en/general-development/feature-proposals.html

Here's some information. In general, how will avail enhance player interaction? How would players interact with avalis?

**Comment by dffdff2423** [comment]
I think giving them a different name might be a good idea. The average player won't be aware of the existing lore, and if any forks want to give them lore that is different to the original cannon they might face player pushback. We have already had some minor issues on CD with players assuming that everyone playing Avali is following their lore.

**Comment by VasilisThePikachu** [comment]
Heyo, there was some maintainer discussion about how we should be handling new species docs. And until then it has been decided to **freeze new species and temporary close all prs until we have decided how species should be done**

I apologize for any inconvenience this may cause.

You are more then welcome to request to reopen this PR when the freeze for new species is lifted.

**Pull request closed without merging**
