### PR TITLE
Neutral Antag proposal: Pizza Delivery Critter

### PR DESCRIPTION
**Pull request by FairlySadPanda**
# Arnold's Pizza Needs You!

image

- Alone?
- Gullible?
- Poor?
- Unaware of our reputation?

If most/all of these apply to you, _or_ we've successfully kidnapped you from your home, then Arnolds Pizza has a job with your name on it!

We need delivery critters willing to do one of the most difficult and thankless tasks in known space: delivering pizzas to NanoTrasen employees!

NanoTrasen knows we make the best pizza in the galaxy*. That's why they have an exclusive contract with us to fulfil their Random Reward Pizza employee satisfaciton scheme. However, NanoTrasen's boutique, black-ops and (frequently) badly-maintained space stations are both challenging to access and deliver to. The fell-off-a-back-of-a-van BlueSpace teleporation devices that we use for such challenging customers are both extremely unethical *and\* have a carry-limit small enough that we can't send a full-sized sapient creature through with our KeepWarm pizza boxes in tow!

That means there's a _unique_ and _exciting_ opportunity for small, light, _expendable_ critters in our delivery services. Join today, and we promise that we'll let you leave afterward. Just remember to get that receipt!

*As do the Syndicate, but we don't tell them that.

---

Note that this PR makes no suggestion for what the delivery critters should look like. The illustrative art above is just where my brainrot took me when designing this feature.

### CODE REVIEW

**Comment by FairlySadPanda** [comment]
It's not in this design doc atm, but there's the concept that the driver might need to deliver another pizza after a few minutes, ad infinatum until they teleport home or the round ends. Not sure on this as "the pizza delivery driver joined the crew" is good fiction, but a frantic delivery driver running around the station repeatedly is funny.

**Comment by HoidC** [comment]
why call it an antag if it isn’t one

it’s not an antagonist it’s just a ghost role

**Comment by FairlySadPanda** [comment]
It's an antag with objectives, in-code using GenericAntagComponent etc. It has the ability to zoom into badly-protected armouries and steal a gun and wage pizza-delivering war, and unlike Pun it isn't crew. It can also be directly used by tots and nukies.

It's in the same "neutral antag" group as the Closet Skeleton.

**Comment by HoidC** [comment]
are you not just going to be banned if you escalate to violence to solve a problem that is really not a problem considering you can glide under every single door between you and your target

**Comment by deltanedas** [comment]
only way this could be seen as an antagonist is a shitter that wants to round remove you refusing to sign, and there was a mechanic that you could cut their hand off or something in response

**Comment by Hmeister-real** [comment]
i really really like this

**Comment by FairlySadPanda** [comment]
> only way this could be seen as an antagonist is a shitter that wants to round remove you refusing to sign, and there was a mechanic that you could cut their hand off or something in response

Probably should be in the doc, but the critter can force an unconscious or cuffed person to sign for the pizza. Will note that in and how it works tomorrow.

**Review by PJB3005 — APPROVED** [review]
Fast track this shit with nepotism

**Comment by Partmedia** [comment]
Would you mind adding a sidebar entry via `src/SUMMARY.md`? Thanks!

**Review by Partmedia — APPROVED** [review]

**Comment by FairlySadPanda** [comment]
@Jezithyr considering it auto-requested you I'd like your input

**Comment by HoidC** [comment]
> > only way this could be seen as an antagonist is a shitter that wants to round remove you refusing to sign, and there was a mechanic that you could cut their hand off or something in response
> 
> Probably should be in the doc, but the critter can force an unconscious or cuffed person to sign for the pizza. Will note that in and how it works tomorrow.
> 
> Given these critters can be used to deliver _comedically large bombs_, you can understand that a suspicious person might not sign for the pizza that NT apparently ordered for them.
> 
> But look at it. It's adorable. You can't just doom it to death, can you?

if you’re assuming they’re carrying a large bomb instead of a pizza that’s kind of metagaming a bit

**Comment by Jezithyr** [comment]
This is the single best antagonist I've ever seen. How can I press the merge button more than once?

**Comment by 6SpadesLuke** [comment]
cant wait to put minibombs in its storage bag

**Comment by TokenStyle** [comment]
Is someone currently developing this amazing design doc? It would be amazing if it appear in game

**Comment by TokenStyle** [comment]
Found it, it's under development by FairlySadPanda
https://github.com/space-wizards/space-station-14/pull/28796

I believe it would be awesome, wish you best and keep it up!

**Comment by ElPidor** [comment]
its so over 
but the concept pretty nice, hope someone will do one

**Pull request merged**
